branches:
    only:
        - master

language: objective-c
osx_image: xcode8.2
xcode_project: iMindLib.xcodeproj
xcode_scheme: iMindLib-iOS
xcode_sdk: iphonesimulator10.1

notifications:
  slack: imind:VmxAeQTYy3BrScWr40M1lTT7

install:
    - ./install_swiftlint.sh

script:
    - xcodebuild clean build -sdk iphonesimulator -project iMindLib.xcodeproj -scheme iMindLib-iOS CODE_SIGNING_REQUIRED=NO
