branches:
    only:
        - master

language: objective-c
osx_image: xcode8.1
xcode_project: iMindLib.xcodeproj
xcode_scheme: iMindLib-iOS
xcode_sdk: iphonesimulator10.1

notifications:
  slack: imind:VmxAeQTYy3BrScWr40M1lTT7

install:
    - ./scripts/install_swiftlint.sh

script:
    - xcodebuild -project iMindLib.xcodeproj -scheme iMindLib-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES test 
    - ./scripts/test_packagemanagers.sh
after_success:
    - bash <(curl -s https://codecov.io/bash) -cF ios
